### ISSUE TITLE
no such table: cookbook_recipe

### ISSUE THREAD

**Issue by gopalmeena** [realpython/django-redis-cache#1]
After executing python manage.py migrate and python manage.py createsuperuser , when i tried to execute python manage.py loaddata cookbook/fixtures/cookbook.json , it shows that "no such table: cookbook_recipe" .

**Comment by mjhea0** [comment]
Is this still an issue?

**Comment by gopalmeena** [comment]
Yes it is. Please can you fix this?

**Comment by mjhea0** [comment]
Then the migrations are not working correctly. Can you check the DB?

**Comment by gopalmeena** [comment]
Can you elaborate?? I mean what should i check in DB?
I set the name of DB in settings.py than i made migrations but there was no table and i got to know this when i tried to dump data in tables.

**Comment by wedwardbeck** [comment]
I'm hitting the same issue.  no such table: cookbook_recipe

Problem installing fixture 'C:\dev\django-redis\django-redis-cache\cookbook/fixtures\cookbook.json': Could not load cookbook.Recipe(pk=1): no such table: cookbook_recipe

I read the table names in the db and don’t see either recipe or food listed. So something is not picked up in the migration.  Any clues?

**Comment by wedwardbeck** [comment]
I got it working - for me I had to run:
python manage.py makemigrations cookbook
then migrate, then it loaded the recipes.

**Comment by gopalmeena** [comment]
Thanks @wedwardbeck  for giving the solution. But i made my own django application with redis till than.

**Comment by mjhea0** [comment]
@wedwardbeck Should I update the post, adding in -

```
$ python manage.py makemigrations cookbook
```

?

**Comment by mjhea0** [comment]
@gopalmeena ^^

**Comment by gopalmeena** [comment]
Yeah, it will be better if you can add that, so that in future if any developer will go through same commands , they will also get same error, so it will be better if you can update README.rd file. @mjhea0

**Comment by gopalmeena** [comment]
Or if you want i can make changes and will request a PR ?
@mjhea0  @wedwardbeck

**Comment by mjhea0** [comment]
Yes, a PR would be awesome. You can do that here -> https://github.com/realpython/realpython-blog/blob/master/2016/2016-09-20-caching-in-django-with-redis.markdown.

Thanks @gopalmeena!

**Comment by mjhea0** [comment]
https://github.com/realpython/realpython-blog/pull/34
